name: Build Mod Collection

on:
  workflow_dispatch:
    inputs: 
      modname: 
        required: true
        default: 'Rampage'
        description: Please select the mod you would like to build
        type: choice
        options:
        - Rampage
        - No Robtop Logo
  push:
    branches:
      - "**"
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Windows
          os: windows-latest

        - name: macOS
          os: macos-latest

        - name: Android32
          os: ubuntu-latest
          target: Android32

        - name: Android64
          os: ubuntu-latest
          target: Android64

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v4

      - if: github.event.inputs.modname == 'Rampage'
      - name: Build the mod (Rampage)
        uses: geode-sdk/build-geode-mod@main
        with:
          working-directory: ./Misc/Rampage
          bindings: geode-sdk/bindings
          bindings-ref: main
          combine: true
          target: ${{ matrix.config.target }}

      - if: github.event.inputs.modname == 'No Robtop Logo'
      - name: Build the mod (No Robtop Logo)
        uses: geode-sdk/build-geode-mod@main
        with:
          working-directory: ./Visual/No Robtop Logo
          bindings: geode-sdk/bindings
          bindings-ref: main
          combine: true
          target: ${{ matrix.config.target }}
          
  package:
    name: Package builds
    runs-on: ubuntu-latest
    needs: ['build']

    steps:
      - uses: geode-sdk/build-geode-mod/combine@main
        id: build

      - uses: actions/upload-artifact@v4
        with:
          name: Build Output
          path: ${{ steps.build.outputs.build-output }}
